"""Pydantic schemas.

The most important contract here is :class:`QuestionSetFile` — the JSON shape
of a question set on disk. Everything that produces or consumes question sets
(``scripts/seed.py``, ``scripts/generate_questions.py``, the import API
endpoint, and the quiz-forge skill) validates against this one model, so a set
generated by any of them is loadable by all of them.
"""

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field, model_validator


class QuestionType(StrEnum):
    MC = "mc"  # multiple choice, auto-graded
    FLASHCARD = "flashcard"  # open question, self-rated after flipping


class DifficultyTag(StrEnum):
    BASIC = "basic"  # level 1
    INTERMEDIATE = "intermediate"  # level 2
    ADVANCED = "advanced"  # level 3
    EXPERT = "expert"  # level 4
    ULTRA_EXPERT = "ultra-expert"  # level 5


class TypicalityTag(StrEnum):
    """How likely an interviewer is to actually ask this question."""

    STAPLE = "staple"  # asked in almost every interview for the role
    COMMON = "common"  # frequently asked
    OCCASIONAL = "occasional"  # shows up now and then
    CURVEBALL = "curveball"  # rare, but separates the best candidates


class SelfRating(StrEnum):
    NAILED = "nailed"  # scores 1.0
    PARTIAL = "partial"  # scores 0.5
    MISSED = "missed"  # scores 0.0


SELF_RATING_SCORES: dict[SelfRating, float] = {
    SelfRating.NAILED: 1.0,
    SelfRating.PARTIAL: 0.5,
    SelfRating.MISSED: 0.0,
}

DIFFICULTY_FOR_LEVEL: dict[int, DifficultyTag] = {
    1: DifficultyTag.BASIC,
    2: DifficultyTag.INTERMEDIATE,
    3: DifficultyTag.ADVANCED,
    4: DifficultyTag.EXPERT,
    5: DifficultyTag.ULTRA_EXPERT,
}


class QuestionTags(BaseModel):
    """The two mandatory tag dimensions plus free-form topic tags."""

    difficulty: DifficultyTag
    typicality: TypicalityTag
    topics: list[str] = Field(default_factory=list, max_length=8)


class QuestionFile(BaseModel):
    """One question as authored in a question-set JSON file."""

    id: str = Field(pattern=r"^[a-z0-9][a-z0-9-]{1,60}$")
    type: QuestionType
    topic: str = Field(min_length=2, max_length=120)
    prompt: str = Field(min_length=10)
    options: list[str] | None = Field(default=None, min_length=2, max_length=6)
    correct_index: int | None = None
    answer_notes: str = Field(min_length=10)
    difficulty_rationale: str = Field(min_length=5)
    tags: QuestionTags

    @model_validator(mode="after")
    def check_type_consistency(self) -> "QuestionFile":
        """MC questions need options + a valid correct_index; flashcards must have neither."""
        if self.type is QuestionType.MC:
            if self.options is None or self.correct_index is None:
                raise ValueError(f"question {self.id!r}: mc requires options and correct_index")
            if not 0 <= self.correct_index < len(self.options):
                raise ValueError(f"question {self.id!r}: correct_index out of range")
        elif self.options is not None or self.correct_index is not None:
            raise ValueError(f"question {self.id!r}: flashcard must not have options/correct_index")
        return self


class QuestionSetFile(BaseModel):
    """A question-set JSON file — the shared contract described in the module docstring."""

    id: str = Field(pattern=r"^[a-z0-9][a-z0-9-]{1,80}$")
    title: str = Field(min_length=3, max_length=200)
    track: str = Field(pattern=r"^[a-z0-9][a-z0-9-]{1,40}$")
    level: int = Field(ge=1, le=5)
    description: str | None = None
    questions: list[QuestionFile] = Field(min_length=1)

    @model_validator(mode="after")
    def check_unique_question_ids(self) -> "QuestionSetFile":
        seen: set[str] = set()
        for question in self.questions:
            if question.id in seen:
                raise ValueError(f"duplicate question id {question.id!r} in set {self.id!r}")
            seen.add(question.id)
        return self


# ---------------------------------------------------------------------------
# API schemas
# ---------------------------------------------------------------------------


class QuestionOut(BaseModel):
    """A question as served to the frontend.

    This is a single-user study tool, so the correct answer and notes ship with
    the question; the frontend reveals them only when the card is flipped.
    """

    id: str
    set_id: str
    type: QuestionType
    topic: str
    prompt: str
    options: list[str] | None
    correct_index: int | None
    answer_notes: str
    difficulty_rationale: str
    tags: QuestionTags


class QuestionSetSummary(BaseModel):
    id: str
    title: str
    track: str
    level: int
    description: str | None
    question_count: int


class SessionStartRequest(BaseModel):
    track: str
    level: int | None = Field(default=None, ge=1, le=5)
    mode: str = Field(default="level", pattern=r"^(level|typical-drill|custom)$")
    typicality: list[TypicalityTag] | None = None  # filter, e.g. drill only staples
    limit: int = Field(default=20, ge=1, le=100)


class SessionOut(BaseModel):
    id: str
    track: str
    level: int | None
    mode: str
    questions: list[QuestionOut]


class AnswerRequest(BaseModel):
    session_id: str
    question_id: str
    chosen_index: int | None = None  # for mc
    self_rating: SelfRating | None = None  # for flashcard

    @model_validator(mode="after")
    def check_exactly_one_answer_kind(self) -> "AnswerRequest":
        if (self.chosen_index is None) == (self.self_rating is None):
            raise ValueError("provide exactly one of chosen_index or self_rating")
        return self


class AnswerResult(BaseModel):
    question_id: str
    score: float
    correct: bool  # score >= 1.0
    correct_index: int | None
    answer_notes: str


class LevelProgress(BaseModel):
    level: int
    difficulty: DifficultyTag
    total_questions: int
    attempted_questions: int
    accuracy: float | None  # None until something was attempted
    unlocked: bool
    passed: bool  # accuracy >= threshold with sufficient coverage


class TrackProgress(BaseModel):
    track: str
    levels: list[LevelProgress]
    highest_unlocked: int


class TopicStat(BaseModel):
    topic: str
    attempts: int
    accuracy: float


class ExportSummary(BaseModel):
    """Performance export consumed by the quiz-forge skill."""

    generated_at: datetime
    total_answers: int
    tracks: list[TrackProgress]
    weak_topics: list[TopicStat]  # lowest accuracy first
    strong_topics: list[TopicStat]  # highest accuracy first
