"""Question-set endpoints: list what's loaded, import any new set."""

from fastapi import APIRouter, Depends
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.db import get_session
from app.models import Question, QuestionSet
from app.schemas import QuestionSetFile, QuestionSetSummary
from app.services import question_sets

router = APIRouter(prefix="/api/sets", tags=["question-sets"])


@router.get("")
def list_sets(session: Session = Depends(get_session)) -> list[QuestionSetSummary]:
    """All loaded question sets with their question counts."""
    rows = session.execute(
        select(QuestionSet, func.count(Question.id))
        .outerjoin(Question, Question.set_id == QuestionSet.id)
        .group_by(QuestionSet.id)
        .order_by(QuestionSet.track, QuestionSet.level, QuestionSet.id)
    ).all()
    return [
        QuestionSetSummary(
            id=qs.id,
            title=qs.title,
            track=qs.track,
            level=qs.level,
            description=qs.description,
            question_count=count,
        )
        for qs, count in rows
    ]


@router.post("/import")
def import_set(
    data: QuestionSetFile, session: Session = Depends(get_session)
) -> QuestionSetSummary:
    """Import (or update) a question set from its JSON representation.

    The body is the same schema as the files in ``data/question_sets/``, so any
    set — hand-written, generated by ``scripts/generate_questions.py``, or by
    the quiz-forge skill — can be loaded without redeploying.
    """
    question_set = question_sets.upsert_question_set(session, data)
    return QuestionSetSummary(
        id=question_set.id,
        title=question_set.title,
        track=question_set.track,
        level=question_set.level,
        description=question_set.description,
        question_count=len(data.questions),
    )
